#!/usr/bin/env python

import subprocess
import shlex
import cmd
import sys

class Repl(cmd.Cmd):
    def default(self, line):
        if line == 'EOF':
            return

        if self.one:
            args = [line]
        else:
            args = shlex.split(line)

        self.run(self.prefix + args)

    def postcmd(self, stop, line):
        if line == 'EOF':
            print
            return True

    def run(self, cmd):
        subprocess.call(cmd)

def repl(prefix, one=False):
    r = Repl()
    r.prefix = prefix
    r.prompt = '$ '
    r.one = one
    r.cmdloop()

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print 'Usage: repl <command> [arg1] ...'
        print
        print ' -1  quote additional input to command'
        sys.exit(1)

    one = False
    if sys.argv[1] == '-1':
        sys.argv.pop(1)
        one = True

    repl(sys.argv[1:], one)
