#!/bin/bash -u

split_file() {
	out="$(echo "$4" | tr '[A-Z]' '[a-z]')"
	count=$(($3 - $2))
	cmd=( dd "if=$1" "of=$out" bs=1 "skip=$2" "count=$count" )
	echo "${cmd[@]}"
	${cmd[@]}
	echo
}

file="${@: -1}"
base="$(basename "$file").split"
outdir="$base"
i=0
while [[ -d "$outdir" ]]; do
	let i++
	outdir="${base}.${i}"
done
mkdir "$outdir"

echo 'Running binwalk...'
out=$(binwalk "$@" | tee /dev/stderr | tail -n+4)

if [[ ! -n "$out" ]]; then
	echo "No binwalk output. Exiting."
	exit 1
fi

echo
echo 'Splitting file...'

IFS=$'\n'
last_pos=0
i=0
suffix="header"
for line in $out; do
	pos=$(echo "$line" | awk {'print $1'})
	split_file "$file" "$last_pos" "$pos" "$outdir/$i.$suffix"
	suffix=$(echo "$line" | awk {'print $3'})
	last_pos="$pos"
	let i++
done

pos="$(wc -c "$file" | awk {'print $1'})"
split_file "$file" "$last_pos" "$pos" "$outdir/$i.$suffix"
