#!/bin/bash -u
join <(t=`echo -e '\t'`; ifconfig | egrep -A4 'en[0-9].*:|eth[0-9].*' | egrep -o 'en[0-9][^:]*:|eth[0-9][^ \t]*[ \t]|wlan[0-9][^ \t]*[ \t]|inet (addr:)?([0-9]+\.?){4}' | sed -e 's/addr://' | tr '\n' '\t' | sed -Ee "s/${t}inet//g" -e "s/${t}\$//" | tr '\t' '\n' | sort) <(netstat -nr | egrep 'default|U.*G' | awk '{print $8, $6 ":", "gateway", $2}' | sed -Ee 's/(eth[^ \t]+|wlan[^ \t]+)([^:]+):/\1:/' -e 's/^ +//' | sort)

